### PR TITLE
Prototype to enable vr mode for aquarium

### PR DESCRIPTION
**Pull request by shaoboyan**
This patch is  the prototype to enable vr mode for aquarium.
Currently change view function is not supported.

### CODE REVIEW

**Comment by shaoboyan** [comment]
@greggman  PTAL, thx.

**Comment by shaoboyan** [comment]
ping this PR for reviewing. thx !

**Comment by greggman** [comment]
Sorry, I guess I should have thought it through more. 

How about using the same assets instead of duplicating them?

or if not, at least deleting the source assets

or maybe just make an aquarium-vr.html and aquarium-vr.js in the aquarium folder?

what do you think?

btw: I have no idea how to test this. I don't have any VR equipment except a PSVR and an iPhone with a Google Cardboard type holder.

**Comment by shaoboyan** [comment]
@greggman thx ! I agree with you and will update the patches to re-use the assets under aquarium folder. 

How to test : 
For android, you need daydream and pixel(XL) and chrome for android which enable webvr flags.
For windows, you need htc vive and experimental chrome build here(https://webvr.info/get-chrome/), it seems firefox or servo also supported htc vive.

**Comment by shaoboyan** [comment]
@greggman  the updated patch sets has been uploaded.

BTW : If you review patch "prototype to enable aquarium vr mode", you'll find that enable vr mode won't affect original aquarium logic. vr mode will be enabled only when both WebVR and VR HMD available. And it could be on and off by the new added icon. So maybe we could just apply this patch to aquarium and reduce the duplicated shader/js code. :)

BTW 2 :  About test, I think the phone that install Google VR SDK (using magic window mode) could be used to test this vr mode.

Thx !

**Comment by greggman** [comment]
Looking at the diffs, if you'd like to merge them into the same demo feel free. But, I noticed you commented out the "change view" button and I didn't see that get added back in if it's not vr. Maybe instead hide it if it is vr?

**Comment by shaoboyan** [comment]
@greggman yes, you're right. Currently there are no control panel could be seen in vr mode. And After some consideration, I think the panel need some other works. So, I think your original suggestion is better. We could use aquarium-vr folder as an intermediate state, and then try to added the ready vr mode to current aquarium.

thx for your reviewing !

**Pull request merged**
